-- Falko initial schema
-- Run this against a fresh Postgres database (Supabase or other)
--
-- It creates all the tables used by the application in the correct order
-- so that foreign key references are satisfied.
--
-- Before running, make sure the following extensions are available:
--   uuid-ossp  (for uuid_generate_v4)
--   pgcrypto   (for gen_random_uuid)
--
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- core tables
-- ---------------------------------------------------------------------------

CREATE TABLE public.tiendas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  descripcion text,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  activo boolean DEFAULT true,
  mp_public_key character varying,
  mp_access_token character varying,
  mp_cvu character varying,
  whatsapp character varying,
  instagram character varying,
  email character varying,
  direccion text,
  moneda character varying DEFAULT 'ARS'::character varying,
  timezone character varying DEFAULT 'America/Argentina/Buenos_Aires'::character varying,
  CONSTRAINT tiendas_pkey PRIMARY KEY (id)
);

CREATE TABLE public.usuarios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying UNIQUE,
  usuario character varying UNIQUE,
  contrasena text,
  nombre character varying,
  rol character varying DEFAULT 'operador'::character varying,
  permiso_categorias boolean DEFAULT false,
  permiso_productos boolean DEFAULT false,
  permiso_configuracion boolean DEFAULT false,
  permiso_ordenes boolean DEFAULT false,
  activo boolean DEFAULT true,
  admin boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

CREATE TABLE public.admin_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  action text NOT NULL,
  details text,
  target_id text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT admin_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE public.banners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tipo character varying DEFAULT 'hero'::character varying,
  titulo character varying,
  subtitulo character varying,
  imagen_url text NOT NULL,
  imagen_mobile_url text,
  link_url text,
  link_texto character varying,
  activo boolean DEFAULT true,
  orden integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT banners_pkey PRIMARY KEY (id)
);

CREATE TABLE public.categorias (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  descripcion text,
  imagen_url text,
  icono character varying,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categorias_pkey PRIMARY KEY (id)
);

CREATE TABLE public.subcategorias (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  categoria_id uuid,
  nombre character varying NOT NULL,
  slug character varying NOT NULL,
  descripcion text,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subcategorias_pkey PRIMARY KEY (id),
  CONSTRAINT subcategorias_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id)
);

CREATE TABLE public.colores (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tienda_id uuid,
  nombre character varying NOT NULL,
  codigo character varying NOT NULL,
  hex character varying NOT NULL,
  activo boolean DEFAULT true,
  CONSTRAINT colores_pkey PRIMARY KEY (id),
  CONSTRAINT colores_tienda_id_fkey FOREIGN KEY (tienda_id) REFERENCES public.tiendas(id)
);

CREATE TABLE public.talles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tienda_id uuid,
  nombre character varying NOT NULL,
  codigo character varying NOT NULL,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  CONSTRAINT talles_pkey PRIMARY KEY (id),
  CONSTRAINT talles_tienda_id_fkey FOREIGN KEY (tienda_id) REFERENCES public.tiendas(id)
);

CREATE TABLE public.configuracion (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clave character varying NOT NULL UNIQUE,
  valor jsonb NOT NULL,
  descripcion text,
  tipo character varying DEFAULT 'general'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_pkey PRIMARY KEY (id)
);

CREATE TABLE public.configuraciones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tienda_id uuid,
  clave character varying NOT NULL,
  valor text,
  tipo character varying DEFAULT 'string'::character varying,
  descripcion text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT configuraciones_pkey PRIMARY KEY (id),
  CONSTRAINT configuraciones_tienda_id_fkey FOREIGN KEY (tienda_id) REFERENCES public.tiendas(id)
);

CREATE TABLE public.filtros_especiales (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  clave character varying NOT NULL UNIQUE,
  config jsonb DEFAULT '{}'::jsonb,
  icono text,
  imagen_url text,
  color character varying,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT filtros_especiales_pkey PRIMARY KEY (id)
);

CREATE TABLE public.homepage_sections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tipo character varying NOT NULL,
  referencia_id character varying NOT NULL,
  titulo character varying NOT NULL,
  subtitulo character varying,
  gif_url text,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT homepage_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cupones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  codigo character varying NOT NULL UNIQUE,
  descripcion text,
  tipo character varying NOT NULL DEFAULT 'porcentaje'::character varying,
  valor numeric NOT NULL DEFAULT 0,
  minimo_compra numeric DEFAULT 0,
  max_uso_total integer,
  usos_actuales integer DEFAULT 0,
  config jsonb DEFAULT '{}'::jsonb,
  valido_desde timestamp with time zone,
  valido_hasta timestamp with time zone,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cupones_pkey PRIMARY KEY (id)
);

CREATE TABLE public.deudas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cliente_nombre character varying NOT NULL,
  cliente_apellido character varying,
  cliente_dni character varying,
  cliente_celular character varying,
  cliente_direccion text,
  total_deuda numeric DEFAULT 0,
  historial jsonb DEFAULT '[]'::jsonb,
  estado character varying DEFAULT 'pendiente'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deudas_pkey PRIMARY KEY (id)
);

CREATE TABLE public.drops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  slug text NOT NULL UNIQUE,
  fecha_lanzamiento timestamp with time zone,
  descripcion text,
  imagen_url text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drops_pkey PRIMARY KEY (id)
);

CREATE TABLE public.etiquetas (
  id text NOT NULL,
  nombre text NOT NULL,
  tipo text,
  color text,
  icono text,
  CONSTRAINT etiquetas_pkey PRIMARY KEY (id)
);

CREATE TABLE public.productos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  descripcion text,
  precio numeric NOT NULL DEFAULT 0,
  precio_original numeric,
  categoria_id uuid,
  subcategoria_id uuid,
  stock_actual integer DEFAULT 0,
  stock_minimo integer DEFAULT 0,
  imagenes jsonb DEFAULT '[]'::jsonb,
  variantes jsonb DEFAULT '[]'::jsonb,
  dimensiones jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  activo boolean DEFAULT true,
  destacado boolean DEFAULT false,
  top boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nuevo_lanzamiento boolean DEFAULT false,
  proximamente boolean DEFAULT false,
  descuento_activo boolean DEFAULT false,
  fecha_lanzamiento timestamp with time zone,
  proximo_lanzamiento boolean DEFAULT false,
  proveedor_nombre text,
  proveedor_contacto text,
  precio_costo numeric,
  descuento_porcentaje numeric DEFAULT 0,
  imagen_url text,
  sku text,
  CONSTRAINT productos_pkey PRIMARY KEY (id),
  CONSTRAINT productos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id),
  CONSTRAINT productos_subcategoria_id_fkey FOREIGN KEY (subcategoria_id) REFERENCES public.subcategorias(id)
);

CREATE TABLE public.producto_drops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producto_id uuid NOT NULL,
  drop_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT producto_drops_pkey PRIMARY KEY (id),
  CONSTRAINT producto_drops_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id),
  CONSTRAINT producto_drops_drop_id_fkey FOREIGN KEY (drop_id) REFERENCES public.drops(id)
);

CREATE TABLE public.producto_imagenes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  producto_id uuid,
  url text NOT NULL,
  alt_text character varying,
  orden integer DEFAULT 0,
  es_principal boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT producto_imagenes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.variantes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  producto_id uuid,
  sku character varying,
  talle character varying,
  color character varying,
  color_hex character varying,
  precio_adicional numeric DEFAULT 0,
  stock integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  imagen_url text,
  CONSTRAINT variantes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.proximamente_notificaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  producto_id text NOT NULL,
  notificado boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT proximamente_notificaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE public.ordenes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_orden character varying UNIQUE,
  cliente_nombre character varying NOT NULL,
  cliente_email character varying,
  cliente_telefono character varying,
  subtotal numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  descuento numeric DEFAULT 0,
  envio numeric DEFAULT 0,
  estado character varying DEFAULT 'pendiente'::character varying,
  metodo_pago character varying,
  notas text,
  mercadopago_payment_id character varying,
  mercadopago_status character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tracking_code text,
  tracking_url text,
  direccion_envio text,
  ciudad text,
  provincia text,
  codigo_postal text,
  cliente_dni text,
  total_transferencia numeric,
  transferencia_expiracion timestamp without time zone,
  CONSTRAINT ordenes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.orden_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  orden_id uuid,
  producto_id uuid,
  cantidad integer NOT NULL DEFAULT 1,
  precio_unitario numeric NOT NULL,
  variante_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orden_items_pkey PRIMARY KEY (id),
  CONSTRAINT orden_items_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES public.ordenes(id),
  CONSTRAINT orden_items_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id)
);

CREATE TABLE public.order_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text NOT NULL,
  email text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'unsubscribed'::text])),
  CONSTRAINT order_subscriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE public.resenas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  producto_id uuid,
  cliente_nombre character varying NOT NULL,
  cliente_email character varying,
  calificacion integer CHECK (calificacion >= 1 AND calificacion <= 5),
  comentario text,
  aprobado boolean DEFAULT true,
  destacado boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  comprobante_url text,
  numero_orden text,
  verificado boolean DEFAULT false,
  CONSTRAINT resenas_pkey PRIMARY KEY (id),
  CONSTRAINT resenas_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id)
);

CREATE TABLE public.shipping_senders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  calle character varying NOT NULL,
  numero character varying NOT NULL,
  piso character varying,
  departamento character varying,
  localidad character varying NOT NULL,
  provincia character varying NOT NULL,
  codigo_postal character varying NOT NULL,
  telefono character varying,
  email character varying,
  es_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_senders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.shipping_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  orden_id uuid,
  tracking_number character varying,
  label_url text,
  estado character varying DEFAULT 'generated'::character varying,
  carrier character varying DEFAULT 'correo_argentino'::character varying,
  costo numeric,
  datos_remitente jsonb,
  datos_destinatario jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_history_pkey PRIMARY KEY (id),
  CONSTRAINT shipping_history_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES public.ordenes(id)
);

CREATE TABLE public.stock_movimientos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tienda_id uuid,
  producto_id uuid,
  variante_id uuid,
  tipo character varying NOT NULL,
  cantidad integer NOT NULL,
  stock_anterior integer NOT NULL,
  stock_nuevo integer NOT NULL,
  referencia character varying,
  notas text,
  usuario_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_movimientos_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movimientos_tienda_id_fkey FOREIGN KEY (tienda_id) REFERENCES public.tiendas(id),
  CONSTRAINT stock_movimientos_variante_id_fkey FOREIGN KEY (variante_id) REFERENCES public.variantes(id)
);

